import { useState } from 'react'
import { Axes, Chart, Control, Controls, Insight, Legend, Readouts, VisualCard, chartColors, points } from './VisualPrimitives'

const L=48,T=24,W=342,H=210,B=T+H
const sx=(value:number,max:number,min=0)=>L+(value-min)/(max-min)*W
const sy=(value:number,max:number,min=0)=>T+H-(value-min)/(max-min)*H

function Checklist(){const conditions=['Prețuri și schimburi libere cu străinătatea','Cadru juridic adecvat și efectiv aplicat','Stabilitate macroeconomică','Consensul partenerilor sociali asupra politicii macroeconomice','Sector financiar, bancar și nonbancar bine dezvoltat','Absența obstacolelor la intrarea/ieșirea de pe piață'];const [checked,setChecked]=useState(conditions.map(()=>true)),score=checked.filter(Boolean).length,tone=score===6?'good':score>=4?'accent':'bad',message=score===6?`${score}/6 condiții îndeplinite — economie de piață pe deplin funcțională (ca România, conform Raportului UE din 2004).`:score>=4?`${score}/6 condiții îndeplinite — economie de piață funcțională, dar cu rezerve.`:`${score}/6 condiții îndeplinite — economie de piață încă în tranziție, nu pe deplin funcțională.`;return <VisualCard note={'Bifează condițiile pe care crezi că o economie le îndeplinește chiar acum, și vezi dacă ar fi considerată „funcțională”.'} className="theory-visual"><div className="condition-list">{conditions.map((condition,i)=><label key={condition}><input type="checkbox" checked={checked[i]} onChange={()=>setChecked(current=>current.map((value,j)=>j===i?!value:value))}/><span>{condition}</span></label>)}</div><div className="condition-meter"><i style={{width:`${score/6*100}%`}} data-tone={tone}/></div><Insight tone={tone}>{message}</Insight></VisualCard>}

function Circuit(){return <VisualCard note="Cele două fluxuri se deplasează în sensuri opuse și descriu același schimb economic." className="theory-visual"><Chart label="Circuitul economic: flux real și flux monetar" viewBox="0 0 420 210"><defs><marker id="arrow-real" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M1 1L9 5L1 9" fill="none" stroke={chartColors.blue} strokeWidth="1.7"/></marker><marker id="arrow-money" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M1 1L9 5L1 9" fill="none" stroke={chartColors.coral} strokeWidth="1.7"/></marker></defs><rect x="32" y="83" width="125" height="52" rx="12" className="flow-box"/><rect x="263" y="83" width="125" height="52" rx="12" className="flow-box"/><text x="94" y="114" textAnchor="middle" className="flow-title">Cumpărător</text><text x="325" y="114" textAnchor="middle" className="flow-title">Vânzător</text><line x1="263" y1="58" x2="157" y2="58" stroke={chartColors.blue} strokeWidth="2.5" markerEnd="url(#arrow-real)"/><text x="210" y="45" textAnchor="middle" className="flow-label primary">Flux real: bunul (ex. pâinea)</text><line x1="157" y1="162" x2="263" y2="162" stroke={chartColors.coral} strokeWidth="2.5" markerEnd="url(#arrow-money)"/><text x="210" y="188" textAnchor="middle" className="flow-label danger">Flux monetar: banii</text></Chart><Legend items={[{color:chartColors.blue,label:'Flux real (bunuri și servicii)'},{color:chartColors.coral,label:'Flux monetar (venituri și cheltuieli)'}]}/></VisualCard>}

const utility=[{q:1,total:15,marginal:15},{q:2,total:20,marginal:5},{q:3,total:23,marginal:3},{q:4,total:24,marginal:1},{q:5,total:24,marginal:0},{q:6,total:23,marginal:-1}]
function Utility(){const [q,setQ]=useState(1),p=utility[q-1],interpretation=p.marginal>0?'Umg > 0: fiecare pahar suplimentar încă îți aduce satisfacție (dar tot mai puțină).':p.marginal===0?'Umg = 0: ai atins pragul de saturație — UT e maximă chiar aici.':'Umg < 0: ai depășit pragul de saturație — consumul suplimentar chiar te incomodează.';const coords=(key:'total'|'marginal')=>points(utility.map(v=>({x:sx(v.q,6),y:sy(v[key],27,-5)})));return <VisualCard note="Pe măsură ce bei pahare cu apă, unul după altul, urmărește cum evoluează utilitatea totală (UT) și utilitatea marginală (Umg)." className="theory-visual"><Chart label="Utilitatea totală și marginală pentru pahare succesive de apă"><Axes xLabel="Pahare (Q)" yLabel="Utili"/><line x1={L} y1={sy(0,27,-5)} x2={L+W} y2={sy(0,27,-5)} className="chart-zero-line"/><polyline points={coords('total')} className="chart-line primary"/><polyline points={coords('marginal')} className="chart-line danger"/>{utility.map(v=><g key={v.q}><circle cx={sx(v.q,6)} cy={sy(v.total,27,-5)} r="3" className="dot-primary"/><circle cx={sx(v.q,6)} cy={sy(v.marginal,27,-5)} r="3" className="dot-danger"/></g>)}<circle cx={sx(p.q,6)} cy={sy(p.total,27,-5)} r="7" className="dot-active"/><circle cx={sx(p.q,6)} cy={sy(p.marginal,27,-5)} r="7" className="dot-active"/></Chart><Legend items={[{color:chartColors.blue,label:'Utilitate totală (UT)'},{color:chartColors.coral,label:'Utilitate marginală (Umg)'},{color:chartColors.gold,label:'Valorile selectate'}]}/><Readouts items={[{label:'Utilitate totală',value:`${p.total} utili`},{label:'Utilitate marginală',value:`${p.marginal} utili`,tone:p.marginal<0?'bad':p.marginal===0?'accent':'good'}]}/><Insight tone={p.marginal<0?'bad':p.marginal===0?'accent':'good'}>{interpretation}</Insight><Controls><Control label="Pahare băute" value={q} min={1} max={6} onChange={setQ}/></Controls></VisualCard>}

function MiniDonut({title,items}:{title:string;items:Array<{name:string;value:number}>}){const total=items.reduce((a,b)=>a+b.value,0),circumference=2*Math.PI*54;let offset=0;return <div className="mini-donut"><h5>{title} — {total} u.m.</h5><Chart label={title} viewBox="0 0 180 180"><circle cx="90" cy="90" r="54" className="donut-base"/>{items.map((item,i)=>{const length=item.value/total*circumference,start=offset;offset+=length;const colors=[chartColors.navy,chartColors.blue,chartColors.gold,chartColors.coral,chartColors.teal,'#7d8a80'];return <circle key={item.name} cx="90" cy="90" r="54" fill="none" stroke={colors[i%colors.length]} strokeWidth="25" strokeDasharray={`${length} ${circumference-length}`} strokeDashoffset={-start} transform="rotate(-90 90 90)"/>})}<text x="90" y="86" textAnchor="middle" className="donut-value">{total}</text><text x="90" y="105" textAnchor="middle" className="donut-label">u.m.</text></Chart><div className="donut-key">{items.map((item,i)=>{const colors=[chartColors.navy,chartColors.blue,chartColors.gold,chartColors.coral,chartColors.teal,'#7d8a80'];return <span key={item.name}><i style={{background:colors[i%colors.length]}}/>{item.name} · {item.value}</span>})}</div></div>}
function Budget(){const income=[{name:'Bani de buzunar',value:20},{name:'Alte venituri (bunici)',value:5}],expenses=[{name:'Abonament RATB',value:10},{name:'Bunuri personale',value:2},{name:'Dulciuri',value:1},{name:'Film',value:5},{name:'Îmbrăcăminte',value:5},{name:'Pizza',value:2}];return <div className="budget-donuts"><MiniDonut title="Venituri" items={income}/><MiniDonut title="Cheltuieli" items={expenses}/></div>}

const bianca=[{q:1,x:12,y:16},{q:2,x:11,y:14},{q:3,x:10,y:12},{q:4,x:9,y:10},{q:5,x:8,y:8},{q:6,x:7,y:6}]
function Bianca(){return <VisualCard note="Raporturile Umg/Preț se egalizează la cantitatea 5 pentru fiecare bun." className="theory-visual"><Chart label="Ratele utilitate marginală pe preț pentru covrigi și pateuri"><line x1={L} y1={B} x2={L+W} y2={B} className="chart-axis-line"/><text x={L} y="15" className="chart-axis-label">Umg/Preț</text>{bianca.map((p,i)=>{const group=W/6,x=L+i*group,bw=group*.3;return <g key={p.q}>{p.q===5&&<rect x={x+2} y={T} width={group-4} height={H} className="equilibrium-band"/>}<rect x={x+group/2-bw-2} y={B-p.x/17*H} width={bw} height={p.x/17*H} rx="3" fill={chartColors.blue}/><rect x={x+group/2+2} y={B-p.y/17*H} width={bw} height={p.y/17*H} rx="3" fill={chartColors.coral}/><text x={x+group/2} y={B+20} textAnchor="middle" className={p.q===5?'chart-value':'chart-axis-label'}>Q={p.q}</text></g>})}</Chart><Legend items={[{color:chartColors.blue,label:'Umg(covrigi)/Px'},{color:chartColors.coral,label:'Umg(pateuri)/Py'},{color:chartColors.teal,label:'Echilibru (Q=5)'}]}/></VisualCard>}

function Substitution(){const [workers,setWorkers]=useState(0),extraCapital=2*workers,l1=10-workers,k1=5+extraCapital;return <VisualCard note="Câți muncitori disponibilizezi? Vezi câte unități de capital sunt necesare ca să compensezi, păstrând producția constantă (Rms = 2, ca în exemplul de mai sus)." className="theory-visual"><Chart label="Substituirea muncii cu capital, cu producția constantă"><Axes xLabel="Muncă (L)" yLabel="Capital (K)"/><line x1={sx(10,12)} y1={sy(5,16)} x2={sx(l1,12)} y2={sy(k1,16)} className="chart-guide strong"/><circle cx={sx(10,12)} cy={sy(5,16)} r="6" className="dot-muted"/><text x={sx(10,12)+9} y={sy(5,16)+4} className="chart-small-label">A</text><circle cx={sx(l1,12)} cy={sy(k1,16)} r="7" className="dot-active"/><text x={sx(l1,12)+9} y={sy(k1,16)-8} className="chart-value">B</text></Chart><Legend items={[{color:chartColors.muted,label:'A: combinația inițială'},{color:chartColors.gold,label:'B: după substituire (producție egală)'}]}/><Readouts items={[{label:'Muncitori disponibilizați (ΔL)',value:workers},{label:'Capital suplimentar necesar (ΔK)',value:extraCapital}]}/><Controls><Control label="Muncitori disponibilizați (ΔL)" value={workers} min={0} max={5} onChange={setWorkers}/></Controls></VisualCard>}

const curveSamples=(maxPrice:number,step=1)=>Array.from({length:Math.floor(maxPrice/step)+1},(_,i)=>i*step)
function MarketStatic({surplus=false}:{surplus?:boolean}){const price=surplus?10:3,quantity=surplus?60:30,maxPrice=surplus?30:12,maxQuantity=surplus?100:120,samples=curveSamples(maxPrice,1);return <VisualCard note={surplus?'Zonele colorate arată câștigul consumatorilor și al producătorilor la prețul de echilibru.':'Intersecția curbei cererii cu oferta determină simultan prețul și cantitatea de echilibru.'} className="theory-visual"><Chart label={surplus?'Graficul surplusului consumatorului și producătorului':'Graficul formării prețului de echilibru'}><Axes xLabel="Preț (u.m.)" yLabel="Cantitate (buc.)"/>{surplus&&<><polygon points={`${sx(maxPrice,maxPrice)},${B} ${sx(price,maxPrice)},${B} ${sx(price,maxPrice)},${sy(quantity,maxQuantity)}`} fill={chartColors.blue} opacity=".16"/><polygon points={`${sx(0,maxPrice)},${B} ${sx(price,maxPrice)},${B} ${sx(price,maxPrice)},${sy(quantity,maxQuantity)}`} fill={chartColors.gold} opacity=".2"/></>}<polyline points={points(samples.map(p=>({x:sx(p,maxPrice),y:sy(Math.max((surplus?90:60)-(surplus?3:10)*p,0),maxQuantity)})))} className="chart-line primary"/><polyline points={points(samples.map(p=>({x:sx(p,maxPrice),y:sy(Math.min((surplus?6:10)*p,maxQuantity),maxQuantity)})))} className="chart-line danger"/><line x1={L} y1={sy(quantity,maxQuantity)} x2={sx(price,maxPrice)} y2={sy(quantity,maxQuantity)} className="chart-guide"/><line x1={sx(price,maxPrice)} y1={sy(quantity,maxQuantity)} x2={sx(price,maxPrice)} y2={B} className="chart-guide"/><circle cx={sx(price,maxPrice)} cy={sy(quantity,maxQuantity)} r="7" className="dot-active"/><text x={sx(price,maxPrice)+9} y={sy(quantity,maxQuantity)-9} className="chart-value">E</text></Chart>{surplus?<><Legend items={[{color:chartColors.blue,label:'Surplusul consumatorului'},{color:chartColors.gold,label:'Surplusul producătorului'}]}/><Readouts items={[{label:'Surplusul consumatorului',value:'600 u.u.'},{label:'Surplusul producătorului',value:'300 u.u.'},{label:'Surplusul total',value:'900 u.u.',tone:'good'}]}/></>:<Legend items={[{color:chartColors.blue,label:'Cerere'},{color:chartColors.coral,label:'Ofertă'},{color:chartColors.gold,label:'E (Pe = 3 u.m., Qe = 30 buc.)'}]}/>}</VisualCard>}

function Excess(){const equilibrium=3,[price,setPrice]=useState(equilibrium),demand=Math.max(60-10*price,0),supply=10*price,difference=demand-supply,maxPrice=11.5,maxQuantity=120,samples=curveSamples(12,.5),message=Math.abs(difference)<.15?`La ${price} u.m. (prețul de echilibru): cantitatea cerută = cantitatea oferită = ${demand.toFixed(1)} buc. Piața este în echilibru, fără exces.`:difference>0?`La ${price} u.m.: cantitatea cerută (${demand.toFixed(1)} buc.) > cantitatea oferită (${supply.toFixed(1)} buc.) → exces de cerere (deficit) de ${Math.abs(difference).toFixed(1)} buc. Acesta e efectul unui preț plafon.`:`La ${price} u.m.: cantitatea oferită (${supply.toFixed(1)} buc.) > cantitatea cerută (${demand.toFixed(1)} buc.) → exces de ofertă (excedent) de ${Math.abs(difference).toFixed(1)} buc. Acesta e efectul unui preț podea.`;return <VisualCard note="Alege un preț practicat și observă direct pe grafic distanța dintre cantitatea cerută și cea oferită." className="theory-visual"><Chart label="Exces de cerere sau ofertă la prețul ales"><Axes xLabel="Preț (u.m.)" yLabel="Cantitate (buc.)"/><polyline points={points(samples.map(p=>({x:sx(p,12),y:sy(Math.max(60-10*p,0),maxQuantity)})))} className="chart-line primary"/><polyline points={points(samples.map(p=>({x:sx(p,12),y:sy(10*p,maxQuantity)})))} className="chart-line danger"/><line x1={sx(price,12)} y1={T} x2={sx(price,12)} y2={B} className="chart-guide"/><line x1={sx(price,12)+7} y1={sy(demand,maxQuantity)} x2={sx(price,12)+7} y2={sy(supply,maxQuantity)} className="excess-bracket"/><circle cx={sx(price,12)} cy={sy(demand,maxQuantity)} r="6" className="dot-primary"/><circle cx={sx(price,12)} cy={sy(supply,maxQuantity)} r="6" className="dot-danger"/></Chart><Legend items={[{color:chartColors.blue,label:'Cerere'},{color:chartColors.coral,label:'Ofertă'},{color:chartColors.gold,label:'Diferența (exces) la prețul ales'}]}/><Controls><Control label="Preț practicat (u.m.)" value={price} min={.5} max={maxPrice} step={.5} onChange={setPrice}/></Controls><div className="visual-presets"><button onClick={()=>setPrice(equilibrium)}>Preț de echilibru</button><button onClick={()=>setPrice(1.5)}>Exemplu: plafon (preț mic)</button><button onClick={()=>setPrice(4.5)}>Exemplu: podea (preț mare)</button></div><Insight tone={difference===0?'good':difference>0?'accent':'bad'}>{message}</Insight></VisualCard>}

export function TheoryVisual({type}:{type:string}){if(type==='checklistFunctionala')return <Checklist/>;if(type==='circuitEconomic')return <Circuit/>;if(type==='utilitateChart')return <Utility/>;if(type==='bugetChart')return <Budget/>;if(type==='biancaChart')return <Bianca/>;if(type==='substitutie')return <Substitution/>;if(type==='echilibruStatic')return <MarketStatic/>;if(type==='surplus')return <MarketStatic surplus/>;if(type==='excesExplorer')return <Excess/>;return null}

function Dumbbell({a,b,labelA,labelB,colorA=chartColors.muted,colorB=chartColors.blue}:{a:number;b:number;labelA:string;labelB:string;colorA?:string;colorB?:string}){const max=Math.max(Math.abs(a),Math.abs(b),1)*1.15,x=(v:number)=>35+Math.abs(v)/max*350;return <div className="calculator-visual"><svg viewBox="0 0 420 105" role="img" aria-label={`${labelA}: ${a}; ${labelB}: ${b}`}><line x1="35" y1="52" x2="385" y2="52" className="dumbbell-track"/><line x1={x(a)} y1="52" x2={x(b)} y2="52" stroke={colorB} strokeWidth="5" strokeLinecap="round" opacity=".5"/><circle cx={x(a)} cy="52" r="9" fill={colorA} stroke="#fff" strokeWidth="3"/><circle cx={x(b)} cy="52" r="9" fill={colorB} stroke="#fff" strokeWidth="3"/><text x={x(a)} y="29" textAnchor="middle" className="chart-value">{Number(a.toFixed(2)).toLocaleString('ro-RO')}</text><text x={x(b)} y="29" textAnchor="middle" className="chart-value">{Number(b.toFixed(2)).toLocaleString('ro-RO')}</text><text x="35" y="88" className="chart-axis-label">{labelA}</text><text x="385" y="88" textAnchor="end" className="chart-axis-label">{labelB}</text></svg></div>}

function CompactDonut({segments}:{segments:Array<{label:string;value:number;color:string}>}){const positive=segments.map(s=>({...s,value:Math.max(0,s.value)})),total=positive.reduce((a,b)=>a+b.value,0)||1,c=2*Math.PI*48;let offset=0;return <div className="calculator-visual calculator-donut"><svg viewBox="0 0 180 145" role="img" aria-label={segments.map(s=>`${s.label}: ${s.value}`).join(', ')}><circle cx="90" cy="70" r="48" className="donut-base compact"/>{positive.map(s=>{const length=s.value/total*c,start=offset;offset+=length;return <circle key={s.label} cx="90" cy="70" r="48" fill="none" stroke={s.color} strokeWidth="20" strokeDasharray={`${length} ${c-length}`} strokeDashoffset={-start} transform="rotate(-90 90 70)"/>})}<text x="90" y="68" textAnchor="middle" className="donut-value">{Number(total.toFixed(1)).toLocaleString('ro-RO')}</text><text x="90" y="83" textAnchor="middle" className="donut-label">total</text></svg><Legend items={segments.map(s=>({label:s.label,color:s.color}))}/></div>}

function Gauge({value,max,zones}:{value:number;max:number;zones:Array<{to:number;color:string;label:string}>}){const safe=Math.min(Math.max(value,0),max),angle=Math.PI-(safe/max)*Math.PI,x=120+78*Math.cos(angle),y=112-78*Math.sin(angle);let from=0;const arc=(start:number,end:number)=>{const a1=Math.PI-(start/max)*Math.PI,a2=Math.PI-(end/max)*Math.PI;return `M ${120+78*Math.cos(a1)} ${112-78*Math.sin(a1)} A 78 78 0 0 1 ${120+78*Math.cos(a2)} ${112-78*Math.sin(a2)}`};return <div className="calculator-visual calculator-gauge"><svg viewBox="0 0 240 145" role="img" aria-label={`Valoare pe scală: ${value.toFixed(2)}`}>{zones.map(z=>{const start=from;from=z.to;return <path key={z.label} d={arc(start,z.to)} fill="none" stroke={z.color} strokeWidth="15" strokeLinecap="butt"/>})}<line x1="120" y1="112" x2={x} y2={y} className="gauge-needle"/><circle cx="120" cy="112" r="7" fill={chartColors.navy}/><text x="120" y="137" textAnchor="middle" className="chart-value">{value.toFixed(2)}</text></svg><Legend items={zones.map(z=>({label:z.label,color:z.color}))}/></div>}

function ProfitRadar({values}:{values:number[]}){const max=Math.max(...values,10)*1.2,center={x:120,y:100},radius=68,labels=['RPr/K','RPr/CT','RPr/CA'],polygon=(vals:number[])=>points(vals.map((value,i)=>{const angle=-Math.PI/2+i*2*Math.PI/3,r=radius*value/max;return{x:center.x+Math.cos(angle)*r,y:center.y+Math.sin(angle)*r}}));return <div className="calculator-visual"><svg viewBox="0 0 240 205" role="img" aria-label="Radarul ratelor profitului">{[.25,.5,.75,1].map(r=><polygon key={r} points={polygon([max*r,max*r,max*r])} className="radar-ring"/>)}{[0,1,2].map(i=>{const p=polygon([max,max,max]).split(' ')[i].split(',');return <line key={i} x1={center.x} y1={center.y} x2={p[0]} y2={p[1]} className="radar-axis"/>})}<polygon points={polygon(values)} className="profit-radar"/><text x="120" y="18" textAnchor="middle" className="radar-label">{labels[0]}</text><text x="224" y="166" textAnchor="end" className="radar-label">{labels[1]}</text><text x="16" y="166" className="radar-label">{labels[2]}</text></svg></div>}

function DecisionAxis({cmg,vmg,price}:{cmg:number;vmg:number;price:number}){const max=Math.max(cmg,vmg,price,1)*1.15,x=(v:number)=>35+v/max*350;return <div className="calculator-visual"><svg viewBox="0 0 420 105" role="img" aria-label="Secvența Cmg, Vmg și P pe o axă numerică"><line x1="35" y1="52" x2="385" y2="52" className="dumbbell-track"/>{[[cmg,'Cmg',chartColors.coral],[vmg,'Vmg',chartColors.gold],[price,'P',chartColors.blue]].map(([value,label,color])=><g key={label as string}><circle cx={x(value as number)} cy="52" r="9" fill={color as string} stroke="#fff" strokeWidth="3"/><text x={x(value as number)} y="28" textAnchor="middle" className="chart-value">{value}</text><text x={x(value as number)} y="84" textAnchor="middle" className="chart-axis-label">{label}</text></g>)}</svg></div>}

function CostWaterfall({fixed,variable}:{fixed:number;variable:number}){const total=fixed+variable,max=Math.max(total,1),h=(v:number)=>v/max*120;return <div className="calculator-visual"><svg viewBox="0 0 300 180" role="img" aria-label={`CFM ${fixed}, CVM ${variable}, CTM ${total}`}><line x1="35" y1="145" x2="270" y2="145" className="chart-axis-line"/><rect x="55" y={145-h(fixed)} width="55" height={h(fixed)} rx="5" fill={chartColors.muted}/><rect x="123" y={145-h(total)} width="55" height={h(variable)} rx="5" fill={chartColors.gold}/><line x1="178" y1={145-h(total)} x2="248" y2={145-h(total)} className="chart-guide strong"/><text x="82" y="166" textAnchor="middle" className="chart-axis-label">CFM</text><text x="150" y="166" textAnchor="middle" className="chart-axis-label">CVM</text><text x="248" y={140-h(total)} textAnchor="end" className="chart-value">CTM {total.toFixed(2)}</text></svg></div>}

export function CalculatorVisual({type,values}:{type:string;values:Record<string,number>}) {
  const valid = (...numbers:number[]) => numbers.every(Number.isFinite)
  if(type==='amortizare')return <CompactDonut segments={[{label:'Capital fix (KF)',value:values.total*values.fix/100,color:chartColors.blue},{label:'Capital circulant (KC)',value:values.total*(1-values.fix/100),color:chartColors.coral}]}/>;
  if(type==='rms')return <Dumbbell a={Math.abs(values.y)} b={Math.abs(values.x)} labelA="Wmg(y) substituit" labelB="Wmg(x) substituent" colorA={chartColors.coral}/>;
  if(type==='productivitate'){const a=values.q0/values.l0,b=values.q1/values.l1;return valid(a,b)?<Dumbbell a={a} b={b} labelA="W₀ (inițial)" labelB="W₁ (curent)"/>:null}
  if(type==='costMediu'){const fixed=values.cf/values.q,variable=values.cv/values.q;return valid(fixed,variable)?<CostWaterfall fixed={fixed} variable={variable}/>:null}
  if(type==='rateProfit'){const kf=values.capital*values.fix/100,cost=kf/values.ani+(values.capital-kf)+values.salarii,revenue=values.pret*values.q,profit=revenue-cost,rates=[profit/values.capital*100,profit/cost*100,profit/revenue*100];return valid(...rates)?<ProfitRadar values={rates}/>:null}
  if(type==='elasticitateCerere'){const gauge=Math.abs(-values.q/values.p)*33.33;return valid(gauge)?<Gauge value={gauge} max={100} zones={[{to:30,color:chartColors.gold,label:'Inelastică'},{to:36.66,color:chartColors.blue,label:'Unitară'},{to:100,color:chartColors.teal,label:'Elastică'}]}/>:null}
  if(type==='profitMaxim')return <DecisionAxis cmg={values.cmg} vmg={values.vmg} price={values.pret}/>;
  if(type==='masaMonetara'){const a=values.p*values.q,b=a/values.v;return valid(a,b)?<Dumbbell a={a} b={b} labelA="Valoarea tranzacțiilor (P×Q)" labelB="Masa monetară (M)" colorA={chartColors.gold}/>:null}
  if(type==='dobanda'){const final=values.capital*Math.pow(1+values.rata/100,values.ani);return <Dumbbell a={values.capital} b={final} labelA="Capital inițial (C)" labelB="Sumă finală (SF)"/>}
  if(type==='inflatie'){const rate=values.p1/values.p0*100-100;return valid(rate)?<Gauge value={rate} max={120} zones={[{to:10,color:chartColors.teal,label:'Moderată'},{to:60,color:chartColors.gold,label:'Galopantă'},{to:120,color:chartColors.coral,label:'Spre hiperinflație'}]}/>:null}
  if(type==='randamentActiune')return <Dumbbell a={values.cumparare} b={values.vanzare} labelA="Preț cumpărare" labelB="Preț vânzare"/>;
  if(type==='cursObligatiune'){const course=values.cupon/(values.rata/100);return valid(course)?<Dumbbell a={values.cupon} b={course} labelA="Venit fix (D)" labelB="Curs (Cs)" colorA={chartColors.gold}/>:null}
  if(type==='salariuReal'||type==='rataSomajului'){const employed=values.ocupata,active=values.activa;return <CompactDonut segments={[{label:'Populație ocupată',value:employed,color:chartColors.teal},{label:'Șomeri',value:active-employed,color:chartColors.coral}]}/>}
  if(type==='consumEconomii')return <CompactDonut segments={[{label:'Consum (C₀)',value:values.c0,color:chartColors.blue},{label:'Economii (E₀)',value:values.vd0-values.c0,color:chartColors.teal}]}/>;
  if(type==='pibPeLocuitor'){const a=values.pib0/values.pop0,b=values.pib1/values.pop1;return valid(a,b)?<Dumbbell a={a} b={b} labelA="PIB/loc T₀" labelB="PIB/loc T₁" colorB={b>=a?chartColors.teal:chartColors.coral}/>:null}
  if(type==='soldBugetar')return <Dumbbell a={values.venituri} b={values.cheltuieli} labelA="Venituri" labelB="Cheltuieli" colorA={chartColors.teal} colorB={values.venituri-values.cheltuieli<0?chartColors.coral:chartColors.blue}/>;
  if(type==='eficientaComertExterior'){const cre=values.pie/values.pve,cri=(values.pii-values.taxe)/values.pvi;return valid(cre,cri)?<Dumbbell a={cre} b={cri} labelA="CRE" labelB="CRI" colorA={chartColors.blue} colorB={chartColors.teal}/>:null}
  return null
}
